### ISSUE TITLE
Not responding to links

### ISSUE THREAD

**Issue by nowakedev** [DrelezTM/YouTubeDLWhatsAppBOT#4]
The bot just reads links (bluetick) but doesn't respond. I am running it on CMD Windows.

**Comment by DrelezTM** [comment]
umm sorry, the bot did not respond because the whatsapp-web.js library error / does not support the button.

I'll fix it right away

**Comment by DrelezTM** [comment]
new fixed code : https://github.com/DrelezTM/YouTubeDLWhatsAppBOT/commit/21b7ea0ecd29994d2d5187ac0412274c0f0be4ef

**Comment by nowakedev** [comment]
Working thanks, is there a way the bot could fetch the files with their titles? i.e Song name, Video name.

**Comment by DrelezTM** [comment]
> Working thanks, is there a way the bot could fetch the files with their titles? i.e Song name, Video name.

You can use `ytdl.getInfo(url)` :
```js
let info = await ytdl.getInfo(url);
console.log(info.videoDetails.title); // Title YouTube Video
```

or maybe I'll add a detailed video in the next update.

**Comment by DrelezTM** [comment]
new update, video details https://github.com/DrelezTM/YouTubeDLWhatsAppBOT/commit/2710428114a7c91d757d9a9a8b2ce6d275842984
