### ISSUE TITLE
do you have a guide ?

### ISSUE THREAD

**Issue by TrueIntelligence** [DrelezTM/YouTubeDLWhatsAppBOT#5]
Do you have a guide how to setup this on a server and how to connect it to the number of whatspp? do I need to use the API of meta or what? you showed how it works but not how to set up and deploy ?

**Comment by RifqiIp** [comment]
that's right, no explanation wk

**Comment by EzequielDM** [comment]
[Installation steps](https://github.com/DrelezTM/YouTubeDLWhatsAppBOT?tab=readme-ov-file#installation-)

[Usage guide](https://github.com/DrelezTM/YouTubeDLWhatsAppBOT/tree/main?tab=readme-ov-file#how-to-use-)

**Comment by DrelezTM** [comment]
> [Installation steps](https://github.com/DrelezTM/YouTubeDLWhatsAppBOT?tab=readme-ov-file#installation-)
> 
> [Usage guide](https://github.com/DrelezTM/YouTubeDLWhatsAppBOT/tree/main?tab=readme-ov-file#how-to-use-)

nice, thank you bro 😁😁😁
